### ISSUE TITLE
Users using Tor getting blocked by error

### ISSUE THREAD

**Issue by mariobehling** [OpenTechSummit/opentechsummit.github.io#16]
We have some people here, who cannot access our site, because they get blocked as they are using Tor. What could we do?

See the link here, please:

> https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-
> "Our basic protection level issues CAPTCHA-based challenges to visitors whose IP address has a high threat score. The level for the basic protection is set for each site on CloudFlare by the site owner".

**Comment by tradzik** [comment]
Hi, they can't be blocked as they are using Tor. CF says they need to enter captcha challenge and then their IP/ID is unlocked. The only one requriement is to have cookies enabled in browser.

https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-
