### ISSUE TITLE
Mailadresse für Einreichungen einrichten -> Weiterleitung an Andre

### ISSUE THREAD

**Issue by monic2001** [OpenTechSummit/opentechsummit.github.io#8]

**Comment by mariobehling** [comment]
Einreichungen kommen nicht ueber Email, sondern ueber Formular und erscheinen im Spreadsheet: OpenTechSummit 2015 - Call for Speakers and Projects (Responses)

**Comment by monic2001** [comment]
Das war Andres Wunsch ... Wann biste wieder da?

VG Monic

**Comment by tradzik** [comment]
Hallo, könnten Sie bitte Englisch sprechen? Ich verstehe nicht Deutsch.
Danke schön.
