### ISSUE TITLE
Ladezeit verbessern 

### ISSUE THREAD

**Issue by monic2001** [OpenTechSummit/opentechsummit.github.io#9]
Die Animation idelt am Anfang ewig rum.

**Comment by mariobehling** [comment]
Adding Cloudflare next week.

**Comment by tradzik** [comment]
@mariobehling should I work on cloudflare now?

**Comment by mariobehling** [comment]
can we bring this website to cloudflare as well?
Could you help to make this site faster, e.g. also reduce the video quality here, please?

**Comment by tradzik** [comment]
Ok, sure. Will do when back from school. Which domain should I move to CF?
opentechsummit.de opentechsummit.net or both?

**Comment by mariobehling** [comment]
just opentechsummit.net

Thanks!

**Comment by tradzik** [comment]
Optimized MP4: https://github.com/OpenTechSummit/opentechsummit.github.io/commit/9a7d7816132bfa1e0c878c3566f212cfc220b36d

**Comment by tradzik** [comment]
Moved to Cloudflare

**Comment by tradzik** [comment]
Added Gulp optimization task.

**Comment by tradzik** [comment]
Loading time ~1.3 sec
